name: HTML CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Check HTML file
        run: |
          test -f index.html
          echo "HTML file exists!"

      - name: Show success
        run: echo "HTML CI completed successfully!"
